### ISSUE TITLE
Get the mesh of DQ blending skinning

### ISSUE THREAD

**Issue by sihanli66** [ConstantineRudenko/DQ-skinning-for-Unity#9]
I have implemented the dqbs in my own project. And I want to get the mesh of human model of dqbs in obj format. However, I found i get the obj model of lbs. How can i get the mesh of dqbs? Thank you.

![dqbs in unity](https://user-images.githubusercontent.com/58064039/91283618-68203d80-e7bd-11ea-8e36-63409b4b9d02.png)
![export lbs in obj](https://user-images.githubusercontent.com/58064039/91283629-6bb3c480-e7bd-11ea-8394-135c43a4dad0.png)

**Comment by KosRud** [comment]
The skinned vertex positions are passed to a vertex shader through textures:

https://github.com/ConstantineRudenko/DQ-skinning-for-Unity/blob/d519c5e7bbbbaad38064cb6fdd3224c30a03d922/Code/DQ%20skinning/DualQuaternionSkinner.cs#L144-L157

If you want to extract skinned vertex positions, you need to read them manually from these textures while the script is running. The packing format is in the comment above. Here is how the shader extracts the vertex positions:

https://github.com/ConstantineRudenko/DQ-skinning-for-Unity/blob/d519c5e7bbbbaad38064cb6fdd3224c30a03d922/Code/DQ%20skinning/Shaders/Material/HackedStandard/HackedStandard.shader#L153-L169
